apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-shopping-app
  labels:
    app: java-shopping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-shopping-app
  template:
    metadata:
      labels:
        app: java-shopping-app
    spec:
      containers:
        - name: java-shopping-app
          image: java-shopping-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: java-shopping-service
spec:
  type: NodePort
  selector:
    app: java-shopping-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

